output_dir: "output"
pretrained_sd_path: "pretrained_models/stable-diffusion-v1-5"
pretrained_clip_path: "pretrained_models/clip-vit-base-patch32"

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

description: "### Train Info: train stage 1: GS-Extractor ###"

train_data:
  video_folder: PATH To Your Video Datset
  lut_folder: PATH To Your LUT Datset
  sample_size:  256
  clip_model_path: "pretrained_models/clip-vit-base-patch32"

fusion_blocks: "full"

learning_rate:    1.e-5
train_batch_size: 4

max_train_epoch:      -1
max_train_steps:      110000
checkpointing_steps:  10000
gradient_accumulation_steps: 1

global_seed: 42
mixed_precision_training: True
enable_xformers_memory_efficient_attention: True

is_debug: False
